# Generated by Django 4.1.6 on 2023-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
